title: Agustianes U. S.
description: Software Development & Tech Blog
google_analytics: UA-49661515-1
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
